services:
  postgres:
    image: postgres:16.8
    container_name: crm_poc_postgres
    shm_size: ${PG_SHM_SIZE:-1g}
    environment:
      POSTGRES_USER: ups_user
      POSTGRES_PASSWORD: ups_pass
      POSTGRES_DB: ups_poc
    ports:
      - "5432:5432"
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c track_io_timing=on
      -c max_connections=${PG_MAX_CONNECTIONS:-100}
      -c shared_buffers=${PG_SHARED_BUFFERS:-512MB}
      -c work_mem=${PG_WORK_MEM:-16MB}
      -c max_parallel_workers_per_gather=${PG_MAX_PARALLEL_WORKERS_PER_GATHER:-1}
      -c jit=${PG_JIT:-off}
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
